### ISSUE TITLE
Editing labels

### ISSUE THREAD

**Issue by VeeranjaneyuluToka** [emadboctorx/labelpix#1]
Hi, Load csv file, verify the bounding box labels, correct the wrong labels and save the corrections again as csv?
Thanks,
Veeru.

**Comment by emadboctorx** [comment]
I'm closing this issue because it is unclear to me what you're asking. If there is an issue with the code, please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) along with system and dependency information / versions if necessary.
